### ISSUE TITLE
Integration of `LicenseChecker` as a build tool plugin.

### ISSUE THREAD

**Issue by ddeveloperuch** [cybozu/LicenseChecker#3]
Dear Contributors,
Thank you for the great tool.
I have a question regarding the proper integration of `LicenseChecker` as a build tool plugin (for Swift Package Project).
The documentation has the necessary steps to do this, but I'm a little confused. Do you suggest create a local package dependency for _LicenseChecker_, is this the only way to edit the _Package.swift_ file and create the _Plugins/LicenseCheckerPlugin/main.swift_ file? If so, it would be much easier to add the binary target and plugin to the _Package.swift_ file and add the code of _Plugins/LicenseCheckerPlugin/main.swift_ to the repository. This gives the option straight from Xcode, just add it under the _Run Build Tool Plug-ins_ section in the Target's _Build Phases_ tab (of course after adding package to the project's Package Dependencies).
![__3](https://github.com/cybozu/LicenseChecker/assets/5438527/65e9a226-5350-4a70-b908-a3c8e20af41b)

You can find an example of such approach here: `https://github.com/FelixHerrmann/swift-package-list`.
![__1](https://github.com/cybozu/LicenseChecker/assets/5438527/4426d9da-7aa7-4b3a-bb11-6713c12ad8ba)

**Comment by Kyome22** [comment]
Thanks for reporting the issue.

To run the license-checker command, the user must give the path to the white-list.json file as an argument.
XcodeBuildToolPlugin cannot read a white-list.json file placed in an arbitrary location.
Therefore, if you want to use LicenseChecker in an Xcode Project, you will need to either use a CommandPlugin or create your own XcodeBuildToolPlugin that includes white-list.json in its resources.

Is there any good way to do this?

**Comment by ddeveloperuch** [comment]
> To run the license-checker command, the user must give the path to the white-list.json file as an argument. XcodeBuildToolPlugin cannot read a white-list.json file placed in an arbitrary location....

I'm sure you can put the configuration in the project's root like the SwiftPackageList guys do and use it via the package's `directory` field:

![Screenshot 2024-06-11 at 2 26 05 PM](https://github.com/cybozu/LicenseChecker/assets/5438527/37930d4b-fbf1-4d9d-a03b-723b487611b3)

**Comment by ddeveloperuch** [comment]
Thank you @Kyome22.

**Comment by Kyome22** [comment]
@ddeveloperuch We released ver 1.3.0 and it supports `BuildToolPlugin`.
