### ISSUE TITLE
Update swift-argument-parser to latest

### ISSUE THREAD

**Issue by snic125** [cybozu/LicenseChecker#7]
Could we update the [swift-argument-parser](https://github.com/apple/swift-argument-parser) to latest? 
Because there would be a dependency collision with https://github.com/mono0926/LicensePlist if someone wants to use both tools in one project.

LicenseChecker depends on swift-argument-parser version 1.1.3
LicensePlist depends on swift-argument-parser version >= 1.1.4

**Comment by Kyome22** [comment]
@snic125 Thank you for letting me know. I will update it.
